/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.joeygibson.kotlinlife

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
//    @Test fun testAppHasAGreeting() {
//        val classUnderTest = Main()
////        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
}
